---
tracing_override: ~
data_root_path: '###DEFINED_AT_RUNTIME###'
keystore:
  type: lair_server
  connection_url: '###DEFINED_AT_RUNTIME###'
admin_interfaces:
  - driver:
      type: websocket
      port: '###DEFINED_AT_RUNTIME###'
      danger_bind_addr: ~
      allowed_origins: '###DEFINED_AT_RUNTIME###'
network:
  bootstrap_url: '###DEFINED_AT_RUNTIME###'
  signal_url: '###DEFINED_AT_RUNTIME###'
  base64_auth_material: ~
  webrtc_config:
    iceServers:
      - urls:
          - '###DEFINED_AT_RUNTIME###'
  target_arc_factor: 1
  report: none
  advanced: ~
request_timeout_s: 60
db_sync_strategy: Resilient
tuning_params: ~
tracing_scope: ~
